echo off
git clone https://github.com/aspnet/aspnet-docker
pause
git clone https://github.com/aspnet/Mvc 
git clone https://github.com/aspnet/HttpAbstractions 
git clone https://github.com/aspnet/DnxTools 
git clone https://github.com/aspnet/Stress 
git clone https://github.com/aspnet/Razor 
git clone https://github.com/aspnet/Localization 
git clone https://github.com/aspnet/Common 
git clone https://github.com/aspnet/EntityFramework 
git clone https://github.com/aspnet/Configuration 
git clone https://github.com/aspnet/Hosting 
git clone https://github.com/aspnet/DependencyInjection 
git clone https://github.com/aspnet/KestrelHttpServer 
git clone https://github.com/aspnet/MusicStore 
git clone https://github.com/aspnet/Security 
git clone https://github.com/aspnet/Testing 
git clone https://github.com/aspnet/dnx 
git clone https://github.com/aspnet/Docs 
git clone https://github.com/aspnet/WebHooks 
git clone https://github.com/aspnet/Diagnostics 
git clone https://github.com/aspnet/UserSecrets 
git clone https://github.com/aspnet/CORS 
git clone https://github.com/aspnet/EntityFramework.Docs 
git clone https://github.com/aspnet/jquery-ajax-unobtrusive 
git clone https://github.com/aspnet/jquery-validation-unobtrusive 
git clone https://github.com/aspnet/Session 
git clone https://github.com/aspnet/EventNotification 
git clone https://github.com/aspnet/Microsoft.Data.Sqlite 
git clone https://github.com/aspnet/Caching 
git clone https://github.com/aspnet/Home 
git clone https://github.com/aspnet/dnvm 
git clone https://github.com/aspnet/RazorTooling 
git clone https://github.com/aspnet/Scaffolding 
git clone https://github.com/aspnet/Entropy 
git clone https://github.com/aspnet/Antiforgery 
git clone https://github.com/aspnet/Announcements 
git clone https://github.com/aspnet/Identity 
git clone https://github.com/aspnet/Options 
git clone https://github.com/aspnet/Routing 
git clone https://github.com/aspnet/Universe 
git clone https://github.com/aspnet/SignalR-Client-Cpp 
git clone https://github.com/aspnet/WebSockets 
git clone https://github.com/aspnet/StaticFiles 
git clone https://github.com/aspnet/FileSystem 
git clone https://github.com/aspnet/DataProtection 
git clone https://github.com/aspnet/aspnet.xunit 
git clone https://github.com/aspnet/Coherence 
git clone https://github.com/aspnet/HttpClient 
git clone https://github.com/aspnet/Signing 
git clone https://github.com/aspnet/Performance 
git clone https://github.com/aspnet/BasicMiddleware 
git clone https://github.com/aspnet/SignalR-ServiceBus 
git clone https://github.com/aspnet/Proxy 
git clone https://github.com/aspnet/ServerTests 
git clone https://github.com/aspnet/SignalR-Redis 
git clone https://github.com/aspnet/SignalR-SqlServer 
git clone https://github.com/aspnet/live.asp.net 
git clone https://github.com/aspnet/SignalR-Server 
git clone https://github.com/aspnet/vsweb-publish 
git clone https://github.com/aspnet/vsweb-docs 
git clone https://github.com/aspnet/Tooling 
git clone https://github.com/aspnet/homebrew-dnx 
git clone https://github.com/aspnet/ResponseCaching 
git clone https://github.com/aspnet/BugTracker 
git clone https://github.com/aspnet/SignalR-Client-Java 
git clone https://github.com/aspnet/SignalR-Client-JS 
git clone https://github.com/aspnet/SignalR-Client-Net 
